### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by EmberAnimus** [domtronn/nuzlocke.app#110]
**Describe the bug**
Can't select Wormadam version (renegade platinum)

**To Reproduce**
1. Choose Burmy on a route as an encounter (in my case it was route 202)
2. Click Evolve
3. Only Plant Cloak Wormadam or Mothim is available.

**Expected behavior**
Trash Cloak and Sandy Cloak Wormadam should be available as an option here. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (Build 19045.2728)
 - Chrome (Version 111.0.5563.147)

**Additional context**
Looks like based on the source Pokemon.json that the other Wormadam forms aren't in yet, or to put it another way, that forms of the same pokemon (without having a different name) aren't quite implemented yet.

**Comment by domtronn** [comment]
Hi @EmberAnimus ! Thanks for raising this
For more context, I had to take a dump of the Pokemon.json as a library I was using was deprecated.
It missed out alternate forms, but obviously they're needed for things like wormadam!

I've added them back in now, ✌️
