### ISSUE TITLE
Deleting and/or moving around routes

### ISSUE THREAD

**Issue by thegamingnobody** [domtronn/nuzlocke.app#116]
**Is your feature request related to a problem? Please describe.**

I would love if it were possible to move and/or delete encounter routes. Occasionally there is a route that stays empty for the entire run because while you can get a pokemon there, you aren't able to right now. An example of this is littleroot town in RSE. While you can get one of the johto starters there, that's only for completing the regional dex IIRC, meaning it stays empty for the entire run. 

**Describe the solution you'd like**

Like I said above, I wonder if it is reasonably possible to remove routes/encounters from the list.

**Describe alternatives you've considered**

Being able to move the routes and deciding the order yourself could also be handy, since you sometimes have access to a route that the site shows after a boss battle.

**Additional context**

**Comment by thegamingnobody** [comment]
Hello,

Thanks for the response. I figured the reordering would require a lot of rewriting on the backend, but as a user you never know how something is made! Unless there is a specific reason why the routes are in their current order, maybe they could be reordered on the backend to reflect available routes better? I know this would require a lot of work and research for each game, but it's just an idea. Another random example is route 46 in GSC/HGSS, while you get an encounter there before the first gym, it is located much later in the list.
The deleting/hiding on the other hand would be lovely to have implemented though!

**Comment by domtronn** [comment]
That's exactly it, I've tried to do a lot of research for the order of the routes but given I can't play _every_ game I rely on walkthroughs/documentation/other older nuzlocke trackers as a basis but almost certainly got stuff wrong!

But reordering the existing routes on the backend is easy 🙂  So if there's anything that's wrong/there's a better order I'm happy to fix it, either raising an issue or posting in [Discord](https://discord.gg/2AWpSHac). It'd be really helpful if you can list what location should move and where to move to!

---

I'll leave this issue open for the delete/hiding feature as well and keep you posted

**Comment by domtronn** [comment]
@thegamingnobody you can now hide locations 🎉 

Click on the three dots next to a location to click the hide button. You can reset hidden locations through the settings modal by clicking on the cog.

<img width="213" alt="Screenshot 2023-05-03 at 15 59 42" src="https://user-images.githubusercontent.com/5881414/235955947-62a3c235-4139-4c13-a805

<img width="874" alt="Screenshot 2023-05-03 at 16 00 12" src="https://user-images.githubusercontent.com/5881414/235956072-e560030e-cd0f-4141-9ffd-285167d5d710.png">
-2b1ff2ce7738.png">
