### ISSUE TITLE
Pokemon Changes to wrong version

### ISSUE THREAD

**Issue by supersentai125** [domtronn/nuzlocke.app#122]
**Describe the bug**
A bunch of the pokemon with different regional versions automatically change to them for some reason even when I type in the actual pokemon. It might help to know that Im doing this for a regular pokemon emerald save
For Example: Zigzagoon turns into Galarian Zigzagoon when I type in Zigzagoon into an encounter no matter what I do

**To Reproduce**
1. Go to any encounter
2. Click on the find encounter search bar
3. Type in any pokemon that has regional variants (such as Zigzagoon, Voltorb, or Sandslash)
4. and see that it automatically changes to the regional varient

**Expected behavior**
What is supposed to happen when I type in and click on zigzagoon, its supposed to be a normal zigzagoon

**Screenshots**

![Screenshot_16](https://user-images.githubusercontent.com/43671250/235806203-07152f8d-516b-494f-8510-dac3d94434b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version Latest

**Smartphone (please complete the following information):**

**Additional context**
Im doing this in a regular pokemon emerald save

**Comment by domtronn** [comment]
Hey @supersentai125 ! Thanks for raising this - yeah I had a few people report this issue, but should be fixed now 👍 
Feel free to reopen if this is still happening!
