### ISSUE TITLE
Fire Red Nuzlocke set the wrong Pokemon fro Rival

### ISSUE THREAD

**Issue by p-telling** [domtronn/nuzlocke.app#126]
**Describe the bug**
Fire Red Nuzlocke sets the wrong Pokemon for your rival based on your starter

**To Reproduce**
1. Start new Nuzlocke for Fire Red
2. Select your starter Pokemon
3. Scroll down to first rival fight it it show them having the starter with a weakness to your starter, not a strength as it should be

**Expected behavior**
Rival picks a starter that has a strength vs your starter.

**Comment by domtronn** [comment]
hey @p-telling ! Thanks for raising this, definitely a bug I introduced a few days ago.
I was trying to improve performance of data loading and un-did the bit where data was refreshed on changing the starter type! It would have worked on refresh, however as the data would be fetched for the right starter

I've pushed a fix so it should be working again now 🙂  Sorry for the inconvenience!
