### ISSUE TITLE
Incorrect Trainer Information for Black 2 Challenge Mode

### ISSUE THREAD

**Issue by manuelrcasimiro** [domtronn/nuzlocke.app#66]
After Skyla there are several errors in moves/levels.

**Comment by domtronn** [comment]
Can you elaborate on which ones? 
Even better if you can provide sources for what the teams should be! E.g. Bulbapedia or Serebii pages.

I'll take a look through the data myself though

**Comment by manuelrcasimiro** [comment]
It's been quite awhile so the only instance I remember is:

  *   The Rival battle in Undella Town displays an incorrect team (his starter isn't fully evolved) (https://www.serebii.net/black2white2/rival.shtml)

I also believe that after Lacunosa Town several level caps are wrong although I've not been able to confirm this as it seems documentation for the Black 2 Challenge mode is pretty lackluster.

Sorry for not being more useful.
________________________________
De: Dom Charlesworth ***@***.***>
Enviado: 3 de março de 2023 15:30
Para: domtronn/dc-nuzlocke ***@***.***>
Cc: Manuel Rodrigues Casimiro ***@***.***>; Author ***@***.***>
Assunto: Re: [domtronn/dc-nuzlocke] Incorrect Trainer Information for Black 2 Challenge Mode (Issue #66)


Can you elaborate on which ones?
Even better if you can provide sources for what the teams should be! E.g. Bulbapedia or Serebii pages.

I'll take a look through the data myself though

**Comment by domtronn** [comment]
No that was very useful! And thanks for replying after my hiatus

You're right I left both Serperior and Samurott behind for that rival fight 😅  

Yeah I remember the information for challenge mode being hard to dig up. I've not played it myself but from what I've read it's just the Gym Fights & Elite Four that have different teams?

I think I went through a few walkthroughs to try and find the data.
